[build]
  command = "node scripts/safe-build.js"
  functions = "netlify/functions"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-scheduled-functions"

[build.environment]
  NODE_VERSION = "18"
  SKIP_REDIS = "true"
  REDIS_DISABLED = "true"
  OTEL_SDK_DISABLED = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  SKIP_ENV_VALIDATION = "true"
  NODE_ENV = "production"

[functions]
  node_bundler = "esbuild"

# Scheduled function to process job queue every 5 minutes
[functions.process-job-queue]
  schedule = "*/5 * * * *"
