[build]
  command = "node scripts/safe-build.js"
  functions = "netlify/functions"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  SKIP_REDIS = "true"
  REDIS_DISABLED = "true"
  OTEL_SDK_DISABLED = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  SKIP_ENV_VALIDATION = "true"
  NODE_ENV = "production"

[functions]
  node_bundler = "esbuild"
