openapi: 3.0.0
info:
  title: Job Search API
  version: 1.0.0
  description: Search for jobs with keyword, location, and advanced filters.
paths:
  /api/jobs/search:
    get:
      summary: Search for jobs
      description: Returns a list of jobs matching the search criteria.
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: Keyword(s) to search in job title, description, etc.
        - in: query
          name: location
          schema:
            type: string
          description: City, state, or ZIP code for location-based search
        - in: query
          name: radius
          schema:
            type: number
            format: float
          description: Search radius (in miles or km)
        - in: query
          name: jobType
          schema:
            type: array
            items:
              type: string
          style: form
          explode: true
          description: Filter by job type (e.g., full-time, part-time, contract)
        - in: query
          name: category
          schema:
            type: array
            items:
              type: string
          style: form
          explode: true
          description: Filter by job category/industry
        - in: query
          name: datePosted
          schema:
            type: string
          description: Filter by date posted (e.g., '24h', '7d', '30d', or ISO date range)
        - in: query
          name: sortBy
          schema:
            type: string
            enum: [relevance, date, distance]
          description: Sort results by 'relevance', 'date', 'distance', etc.
        - in: query
          name: order
          schema:
            type: string
            enum: [asc, desc]
          description: Sort order
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number for pagination
        - in: query
          name: pageSize
          schema:
            type: integer
            default: 20
            maximum: 100
          description: Number of results per page
      responses:
        '200':
          description: A list of jobs
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        company:
                          type: string
                        location:
                          type: string
                        type:
                          type: string
                        category:
                          type: string
                        datePosted:
                          type: string
                          format: date-time
                        description:
                          type: string
                        distance:
                          type: number
                        salary:
                          type: string
                        applyUrl:
                          type: string
                  pagination:
                    type: object
                    properties:
                      page:
                        type: integer
                      pageSize:
                        type: integer
                      totalResults:
                        type: integer
                      totalPages:
                        type: integer
        '400':
          description: Invalid parameters
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
