openapi: 3.0.0
info:
  title: Job Search API
  version: 1.0.0
  description: API endpoint for searching job listings with filtering, sorting, and pagination.
servers:
  - url: /api/v1
paths:
  /jobs/search:
    get:
      summary: Search for job listings
      description: Returns a list of job listings matching the search and filter criteria.
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: Search keyword(s) (optional)
        - in: query
          name: location
          schema:
            type: string
          description: City, state, or zip (optional)
        - in: query
          name: radius
          schema:
            type: number
            minimum: 0
          description: Search radius in miles/km (optional)
        - in: query
          name: jobType
          schema:
            type: string
            enum: [full-time, part-time, contract, internship, temporary, other]
          description: Job type (optional)
        - in: query
          name: category
          schema:
            type: string
          description: Job category/industry (optional)
        - in: query
          name: datePosted
          schema:
            type: string
            format: date
          description: Date posted (ISO date or relative, optional)
        - in: query
          name: sortBy
          schema:
            type: string
            enum: [relevance, date]
          description: Sort order (optional)
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Pagination page (optional)
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Results per page (optional)
      responses:
        '200':
          description: A list of job listings
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        company:
                          type: string
                        location:
                          type: string
                        type:
                          type: string
                        category:
                          type: string
                        datePosted:
                          type: string
                          format: date
                        description:
                          type: string
                        applyUrl:
                          type: string
                  pagination:
                    type: object
                    properties:
                      page:
                        type: integer
                      limit:
                        type: integer
                      totalResults:
                        type: integer
                      totalPages:
                        type: integer
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
